alpine_amd64:
    stage: build
    image: alpine:edge
    before_script:
        - ./alpine-depends
    script:
        - ./update-all
        - cd libarchive-qt && mkdir build && cd build && cmake .. && make -kj4 && make install && cd ../..
        - mkdir build && cd build
        - cmake .. && make -kj$(nproc)

archlinux_amd64:
    stage: build
    image: archlinux:latest
    before_script:
        - ./arch-depend
    script:
        - ./update-all
        - cd libarchive-qt && mkdir build && cd build && cmake .. && make -kj4 && make install && cd ../..
        - mkdir build && cd build
        - cmake .. && make -kj$(nproc)

debian_sid_amd64:
    stage: build
    image: debian:sid
    before_script:
        - ./debian-depend
    script:
        - ./update-all
        - cd libarchive-qt && mkdir build && cd build && cmake .. && make -kj4 && make install && cd ../..
        - mkdir build && cd build
        - cmake .. && make -kj$(nproc)
