image: debian:sid

before_script:
    - apt-get update -yq
    - apt-get install -y g++ git ca-certificates make cmake ninja-build
    - apt-get install -y cmake qttools5-dev g++ make libarchive-dev liblzma-dev libbz2-dev zlib1g-dev liblz-dev

build_amd64:
  stage: build
  script:
    - mkdir build && cd build
    - cmake .. && make -kj$(nproc)
