image: ubuntu:xenial

before_script:
    - apt-get update -yq && apt-get install -y qt5-qmake qttools5-dev qtchooser g++ make libarchive-dev liblzma-dev libbz2-dev zlib1g-dev liblz-dev

build_amd64:
  stage: build
  script:
    - qmake -qt5 DEFINES+=HAVE_LZLIB
    - make -j$(nproc)
