debian_sid_amd64:
    stage: build
    image: debian:sid
    before_script:
        - apt-get update -yq
        - apt-get install -y g++ git ca-certificates make cmake ninja-build build-essential fakeroot
        - apt-get install -y cmake qttools5-dev g++ make libarchive-dev liblzma-dev libbz2-dev zlib1g-dev liblz-dev

    script:
        - dpkg-buildpackage -rfakeroot -uc -us

debian_testing_amd64:
    stage: build
    image: debian:sid
    before_script:
        - apt-get update -yq
        - apt-get install -y g++ git ca-certificates make cmake ninja-build build-essential fakeroot
        - apt-get install -y cmake qttools5-dev g++ make libarchive-dev liblzma-dev libbz2-dev zlib1g-dev liblz-dev

    script:
        - dpkg-buildpackage -rfakeroot -uc -us

debian_stable_amd64:
    stage: build
    image: debian:sid
    before_script:
        - apt-get update -yq
        - apt-get install -y g++ git ca-certificates make cmake ninja-build build-essential fakeroot
        - apt-get install -y cmake qttools5-dev g++ make libarchive-dev liblzma-dev libbz2-dev zlib1g-dev liblz-dev

    script:
        - dpkg-buildpackage -rfakeroot -uc -us
